default:
  image: ruby:2.4.2
  before_script:
    - cd reddit
    - bundle install
  services:
    - name: docker:19.03-dind

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build_job:
  # variables:
  #   DOCKER_HOST: tcp://docker:2375
  #   DOCKER_TLS_CERTDIR: ""
  image: docker:19.03
  # services:
  #   - docker:dind
  stage: build
  tags:
    - dind
  before_script:
    - docker info
    - echo $CI_SERVER_HOST
    # - pwd
    # - ls -la
  script:
    - cd reddit && docker build -t reddit-$CI_COMMIT_REF_NAME:$CI_PIPELINE_IID .
    - docker tag reddit-$CI_COMMIT_REF_NAME:$CI_PIPELINE_IID sjotus/gitlab-reddit:$CI_PIPELINE_IID
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
    - docker push sjotus/gitlab-reddit:$CI_PIPELINE_IID

test_unit_job:
  stage: test
  tags:
    - docker
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

.test_integration_job:
  stage: test
  tags:
    - docker
  script:
    - echo 'Testing 2'

.deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  image: docker:19.03
  variables:
    DOCKER_HOST: tcp://$CI_SERVER_HOST:2375
  stage: review
  tags:
    - docker
  before_script:
    - docker info
    - echo $CI_SERVER_HOST
  script:
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - docker run -d --rm -p 9292:9292 sjotus/gitlab-reddit:$CI_PIPELINE_IID
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
