FROM grafana/grafana:5.0.0

COPY dashboards /var/lib/grafana/dashboards
ADD provisioning/dashboards /etc/grafana/provisioning/dashboards
ADD provisioning/datasources /etc/grafana/provisioning/datasources
