global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitriy_usachev'
