version: '3.5'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.8.3
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.8.3
    ports:
      - "5601:5601"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - reddit_back
      - reddit_front

networks:
  reddit_front:
    name: reddit_front_net
    driver: bridge
  reddit_back:
    name: reddit_back_net
    driver: bridge
