version: '3.5'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.8.3
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.8.3
    ports:
      - "5601:5601"
