version: '3.5'
services:
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - reddit_front
      - reddit_back
      - prometheus

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - prometheus

  mongodb-exporter:
    image: ${USERNAME}/mongodb-exporter
    command:
      - '--mongodb.uri=mongodb://post_db'
      - '--collect.database'
    networks:
      prometheus:
        aliases:
          - mongodb-exporter
      reddit_back:

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.14.0
    ports:
      - '9115:9115'
    # volumes:
    #   - '../monitoring/exporters/blackbox-exporter:/config'
    # command:
    #   - '--config.file=/config/blackbox.yml'
    networks:
      - prometheus
      - reddit_front
      - reddit_back

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - prometheus

  telegraf:
    image: ${USERNAME}/telegraf
    networks:
      - prometheus
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  grafana:
    image: ${USERNAME}/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - prometheus

  alertmanager:
    image: ${USERNAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - prometheus

  stackdriver-exporter:
    image: frodenas/stackdriver-exporter
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/gcp-cred/gcp-stackdriver-docker-key.json
      - STACKDRIVER_EXPORTER_GOOGLE_PROJECT_ID=docker-248611
      - STACKDRIVER_EXPORTER_MONITORING_METRICS_TYPE_PREFIXES=compute.googleapis.com/instance/cpu,compute.googleapis.com/instance/disk
    ports:
      - 9255:9255
    networks:
      - prometheus
    volumes:
      - /var/gcp-cred:/var/gcp-cred

volumes:
  prometheus_data:
  grafana_data:

networks:
  prometheus:
    name: prometheus_net
    driver: bridge
  reddit_front:
    name: reddit_front_net
    driver: bridge
  reddit_back:
    name: reddit_back_net
    driver: bridge
