---
# etcd playbook
- name: Configure etcd
  hosts: controller
  become: yes
  tasks:
    - name: Download etcd
      unarchive:
        src: https://github.com/coreos/etcd/releases/download/v3.3.13/etcd-v3.3.13-linux-amd64.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts: [--strip-components=1]
        exclude: ["Documentation", "*.md"]

    - name: Create additional directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "/etc/etcd"
        - "/var/lib/etcd"

    - name: Copy certificates
      copy:
        src: "{{ item }}"
        dest: /etc/etcd/
      with_items:
        - "../ssl/ca.pem"
        - "../ssl/kubernetes-key.pem"
        - "../ssl/kubernetes.pem"

    - name: Create etcd.service
      template:
        src: ../templates/etcd.service.j2
        dest: /etc/systemd/system/etcd.service
      notify:
        - restart etcd

    - name: Enable etcd.service
      systemd:
        name: etcd.service
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: restart etcd
      systemd:
        name: etcd.service
        daemon_reload: yes
        state: restarted
