---
# Configure local kubectl
- name: Configure local kubectl
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  # vars:
  #   kube_ip:
  #     KUBERNETES_PUBLIC_ADDRESS: |
  #       $(gcloud compute addresses describe kubernetes-the-hard-way \
  #         --region $(gcloud config get-value compute/region) \
  #         --format 'value(address)')
  tasks:
    - name: Get kube external ip
      shell: |
        export KUBERNETES_PUBLIC_ADDRESS=$(gcloud compute addresses describe kubernetes-the-hard-way \
          --region $(gcloud config get-value compute/region) \
          --format 'value(address)') \
          && echo $KUBERNETES_PUBLIC_ADDRESS
      register: kube_ip

    - name: Show env
      debug:
        msg: "{{ kube_ip.stdout }}"

    - name: kubectl set-config
      shell: |
        kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=../kube-files/ca.pem \
        --embed-certs=true \
        --server=https://{{ kube_ip.stdout }}:6443

    - name: kubectl set-credential
      shell: |
        kubectl config set-credentials admin \
        --client-certificate=../kube-files/admin.pem \
        --client-key=../kube-files/admin-key.pem

    - name: kubectl set-context
      shell: |
        kubectl config set-context kubernetes-the-hard-way \
        --cluster=kubernetes-the-hard-way \
        --user=admin

    - name: kubectl use-context
      shell: kubectl config use-context kubernetes-the-hard-way
