---
- name: Gather Facts
  hosts: all
  gather_facts: yes
  tasks: []

- name: Prerequisites
  hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - name: "Get hosts"
      debug:
        msg: |
          {% for host in groups['controller'] %}
            "{{ hostvars[host]['ansible_facts']['hostname'] }}"
          {% endfor %}

    # - name: hostname
    #   debug:
    #     msg: "{{ hostname }}"
 #     delegate_to: localhost
