groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0 # любое PromQL выражение
      for: 1m       # В течении какого времени, по умолчанию 0
      labels:       # Дополнительные метки
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'

    - alert: HighRequestLatency
      expr: histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le)) > 0.1
      for: 10s
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has hight response latency'
        summary: 'Instance {{ $labels.instance }} has hight response latency'
