version: '3.5'
services:
  ui:
    volumes:
      - ./ui:/app
    command: ["puma", "--debug", "-w", "2"]
  post:
    volumes:
      - ./post:/app
  comment:
    volumes:
      - ./post-py:/app
    command: ["puma", "--debug", "-w", "2"]
