---
- name: Install dependencies
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    filename: docker
    state: present

- name: Install docker
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: present

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ deploy_user }}"
    append: yes
    groups: docker

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes
