Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |v|
		v.memory = 512
	end
	#config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "docker"
    db.vm.network :private_network, ip: "10.10.10.100"

    # db.vm.provision "ansible" do |ansible|
    # 	ansible.playbook = "playbooks/packer_docker.yml"
    # 	ansible.groups = {
    # 		"db" => ["dbserver"],
    # 		"db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
    # 	}
    	
    # end
  end
  
end
